<?php
$gift=Mage::registry('giftinfo');
$action=Mage::getBaseUrl().'csgiftcard/gift/csredeemsuccess';
?>

<div class="page-title">
    <h1>Redeem Giftcard</h1>
</div>

<form action="<?php echo $action;?>" id="csgift-cardredeem" method="post">
    <div class="fieldset">    
        <ul class="form-list">             
            <li class="wide">
                <label for="cs_giftmessage">Gift Message</label>
                <div class="input-box">
                    <textarea name="cs_giftmessage" id="cs_giftmessage" title="Gift Message" cols="5" rows="3" readonly>
                    <?php echo $gift['gift_message'];?>
                    </textarea>
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">      
        <input type="hidden" name="order_id" id="order_id" value="<?php echo $gift['order_id'];?>">  
        <button type="submit" title="Get My Card" class="button"><span><span>Get My Card</span></span></button>
    </div>
</form>