<?php
$action=Mage::getBaseUrl().'csgiftcard/';
?>
<form id="csgift-coupon-form" action="<?php echo $action;?>" method="post">
    <div class="csgift">
        <h2>Gift Codes</h2>
        <div class="csgift-form">
            <label for="csgift_code">Gift Codes</label>
            <input type="hidden" name="remove" id="remove-code" value="0">
            <div class="field-wrapper">
                <input class="input-text" type="text" id="csgift_code" name="csgift_code" value="">
                <div class="button-wrapper">
                    <button type="button" title="Apply" class="button2" onclick="csgiftForm.submit(false)" value="Apply">
                        <span><span>Apply</span></span>
                    </button>
                </div>
            </div>
        </div>
    </div>
</form>

<script type="text/javascript">
//<![CDATA[
var csgiftForm = new VarienForm('csgift-coupon-form');
csgiftForm.submit = function (isRemove) {
    if (isRemove) {
        $('csgift_code').removeClassName('required-entry');
        $('remove-code').value = "1";
    } else {
        $('csgift_code').addClassName('required-entry');
        $('remove-code').value = "0";
    }
    return VarienForm.prototype.submit.bind(csgiftForm)();
}
//]]>
</script>
