<?php 
$orderId=Mage::registry('order_id');
$recipientModel=Mage::getModel('csgiftcard/recipient')->load($orderId,'order_id');
//based on the order id need to make the api call for create new giftcard
$barcodeString='J3D3C 5E655 87EPM RH5N6'; //sample sandbox card    
$img=Mage::helper('csgiftcard')->getBarCode128($barcodeString);
?>


<ul class="messages mail-success-msg" style="display:none">
   <li class="success-msg">
      <ul>        
         <li><span id='mail-message'></span></li>
      </ul>
   </li>
</ul>

<ul class="messages mail-error-msg" style="display:none">
<li class="error-msg"><ul><li><span id='mail-error'></span></li></ul></li>
</ul>

<div id='printpage'>
<div class="page-title">
    <h1>Your Giftcard Informations</h1>
</div>
 <div class="fieldset">               
        <ul class="form-list">
            <li class="fields">
                
                <div class="field">
                    <label for="csgiftcard-no">Giftcard Number</label>
                    <div class="input-box">
                       <span><?php echo $barcodeString;?></span>
                    </div>
                </div>
            </li>                       

            <li class="fields">                
                <div class="field">
                    <label for="csgiftcard-no-barcode">Giftcard Barcode</label>
                    <div class="csgiftcard-no-barcode">
                       <img src="<?php echo $img;?>" alt="Gift Card Barcode"/>
                    </div>
                </div>
            </li>                       
        </ul>
    </div>
    <div class="buttons-set">
        <input type="hidden" name="sender_name" id="sender_name" value="">
        <button type="button" id= "send_email" title="Send Email" class="button"><span><span>Send Email</span></span></button>
        <button type="button" onclick="printContent('printpage')" title="Print" class="button"><span><span>Print</span></span></button>
    </div>
</div>

<script type="text/javascript">
jQuery("#send_email").click(function(){
                var data={};
                data['card_no'] = '<?php echo $barcodeString;?>';
                data['barcode_img'] = '<?php echo $img;?>';
                data['recipient_name'] = "<?php echo $recipientModel['recipient_name'];?>";
                data['recipient_email'] = "<?php echo $recipientModel['recipient_email'];?>";               
               
                jQuery.ajax({
                  url:'<?php echo Mage::getBaseUrl().'csgiftcard/gift/cssendcard';?>',
                  type:'POST',
                  data:data,
                  dataType:'json',
                  success: function(result) {   
                  if(result.success){  
                  jQuery('#mail-message').text(result.msg);               
                  jQuery('.mail-success-msg').show();
                }
                else
                {
                 jQuery('#mail-error').text(result.msg);               
                 jQuery('.mail-error-msg').show();
                }
                  }                 
                    });                
});

function printContent(el){
	var restorepage = document.body.innerHTML;
	var printcontent = document.getElementById(el).innerHTML;
	document.body.innerHTML = printcontent;
	window.print();
	document.body.innerHTML = restorepage;
}       
</script>